const dataSpesialis = [
    "Spesialis Akupunktur Medik",
    "Spesialis Anak",
    "Spesialis Andrologi",
    "Spesialis Anestesiologi dan Terapi Intensif",
    "Spesialis Bedah",
    "Spesialis Bedah Anak",
    "Spesialis Bedah Mulut",
    "Spesialis Bedah Plastik Rekonstruksi dan Estetik",
    "Spesialis Bedah Saraf",
    "Spesialis Bedah Toraks Kardio Vaskular",
    "Spesialis Dermatologi dan Venereologi",
    "Spesialis Emergency Medicine",
    "Spesialis Farmakologi Klinik",
    "Spesialis Forensik dan Medikolegal",
    "Spesialis Gizi Klinik",
    "Spesialis Jantung dan Pembuluh Darah",
    "Spesialis Kedokteran Fisik dan Rehabilitasi",
    "Spesialis Kedokteran Kelautan",
    "Spesialis Kedokteran Keluarga Layanan Primer",
    "Spesialis kedokteran nuklir",
    "Spesialis Kedokteran Okupasi",
    "Spesialis Kedokteran Olah Raga",
    "Spesialis Kedokteran Penerbangan",
    "Spesialis Kesehatan Jiwa",
    "Spesialis Mata",
    "Spesialis Mikrobiologi Klinik",
    "Spesialis Neurologi (Saraf)",
    "Spesialis Obstetri dan Ginekologi",
    "Spesialis Onkologi Radiasi",
    "Spesialis Orthopaedi dan Traumatologi",
    "Spesialis Parasitologi Klinik",
    "Spesialis Patologi Anatomi",
    "Spesialis Patologi Klinik",
    "Spesialis Penyakit Dalam",
    "Spesialis Pulmonologi dan Kedokteran Respirasi",
    "Spesialis Radiologi",
    "Spesialis THT-KL",
    "Spesialis Urologi"
];

module.exports = dataSpesialis;